name: Auto approval of pull requests in Github
on: 
   pull_request: 
    types: ['opened', 'reopened']
   
jobs: 
  auto-approve:
    runs-on: ubuntu:latest 
    steps: 
    - name: Checkout code
      uses: actions/checkout@v4.1.1
      with: 
       token: ${{ secrets.GITHUB_TOKEN }}    
    - name: Check existence of the file in sonarqube repository
      uses: thebinaryfelix/check-file-existence-action@v1
      with: 
        files: 'value-stream-requests/ggg-tools-build-*.yaml' 

    - name: Setup Python in runner
      uses: actions/setup-python@v3
      with: 
        python-version: '3.x'

    - name: Install dependencies
      run: python -m pip install pyyaml
   
    - name: Check config fields in example file
      id: validate_yaml
      run: |
        import yaml 
         required_keys {
             - 'projectName': 
               'projectKey': 
               'mainBranch': main
               'qualityGate': 
               'qualityProfiles':
                  - name: 
                    language: 
                    parent: 
         }
        with open('ggg-tools-build*.yaml', r) as f:
          config = yaml.safe_load(f)
             def check_keys(expected, actual):
              for key,value in expected.items():
                if key not in actual:
                  raise valueError(f"Key '{key} is missing from YAML file")
                if isInstance(value, dict):
                  check_keys(value, actual[key])
                elif value is not None and actual[key] != value:
                  raise valueError(f"Key '{key}' does not have the expected '{value}'.")
             check_keys(required_keys, config)     

    - name: Automate the approval of PRs
      if: steps.validate_yaml.conclusion == 'success'
      uses: hmarr/auto-approve-action@v2.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

